package Vista;
import JerarquiaHerencia.*;
import Publicaciones.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Consultar extends javax.swing.JPanel {

    JTextArea datos;
    DefaultTableModel model = new DefaultTableModel();
    tablaLibros tl;
    tablaRevistas tr;
    tablaPeriodicos tp;
    ManPublic mp = new ManPublic();

    public Consultar() {
        initComponents();
        datos = new JTextArea();
        tl = new tablaLibros();
        tr = new tablaRevistas();
        tp = new tablaPeriodicos();

        Contenedor.add(tl);
        Contenedor.add(tr);
        Contenedor.add(tp);

        tl.setVisible(false);
        tr.setVisible(false);
        tp.setVisible(false);
        //  Contenedor.add(tabla);
        
        

    }
    
    public void mostrarDatos(){
        tl.limpiarT();
        tr.limpiarT();
        tp.limpiarT();
        mp.tablas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();
        Contenedor = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btn1.setText("libros");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setText("Revistas");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setText("Periodicos");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        jPanel1.add(txtBuscar);

        btn4.setText("jButton4");
        jPanel1.add(btn4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
        add(Contenedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

        tl.setVisible(true);
        tr.setVisible(false);
        tp.setVisible(false);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        tl.setVisible(false);
        tr.setVisible(true);
        tp.setVisible(false);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
       
        tl.setVisible(false);
        tr.setVisible(false);
        tp.setVisible(true);
    }//GEN-LAST:event_btn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
