/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import JerarquiaHerencia.ClassLibro;
import JerarquiaHerencia.ClassPublicaciones;
import Publicaciones.ManPublic;
import java.awt.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vargas Baltazar
 */
public class FrmAltaLibro extends javax.swing.JPanel {

    /**
     * Creates new form FrmçAltaLibro
     */
   
    
    public FrmAltaLibro() {
 
        initComponents();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpo7 = new fondoPanel1();
        txtPrecio = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtEdiccion = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtNPaginas = new javax.swing.JTextField();
        encabezado = new fondoPanel();
        jLabel7 = new javax.swing.JLabel();
        margen = new fondoPanel2();

        setBackground(new java.awt.Color(153, 207, 234));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        setPreferredSize(new java.awt.Dimension(400, 380));
        setLayout(new java.awt.BorderLayout());

        txtPrecio.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreciotxtPrecioActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 51, 153));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Titulo:");

        txtEdiccion.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtEdiccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicciontxtEdiccionActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 51, 153));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setText("Precio:");

        jLabel46.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 51, 153));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("Nº De Páginas:");

        btnCancelar.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarjButton1ActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 51, 153));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("Autor:");

        btnAceptar.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(51, 153, 0));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarbtnAceptarActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 51, 153));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("ISBN:");

        jLabel49.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 51, 153));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Edicción:");

        txtTitulo.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitulotxtTituloActionPerformed(evt);
            }
        });

        txtAutor.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutortxtAutorActionPerformed(evt);
            }
        });

        txtISBN.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNtxtISBNActionPerformed(evt);
            }
        });

        txtNPaginas.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        txtNPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNPaginastxtNPaginasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuerpo7Layout = new javax.swing.GroupLayout(cuerpo7);
        cuerpo7.setLayout(cuerpo7Layout);
        cuerpo7Layout.setHorizontalGroup(
            cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuerpo7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuerpo7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cuerpo7Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(31, 31, 31)
                        .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        cuerpo7Layout.setVerticalGroup(
            cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuerpo7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txtNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEdiccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addGap(23, 23, 23)
                .addGroup(cuerpo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(cuerpo7, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Registro De Un Libro");
        encabezado.add(jLabel7);

        add(encabezado, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout margenLayout = new javax.swing.GroupLayout(margen);
        margen.setLayout(margenLayout);
        margenLayout.setHorizontalGroup(
            margenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        margenLayout.setVerticalGroup(
            margenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        add(margen, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNPaginastxtNPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNPaginastxtNPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNPaginastxtNPaginasActionPerformed

    private void txtISBNtxtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNtxtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNtxtISBNActionPerformed

    private void txtAutortxtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutortxtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutortxtAutorActionPerformed

    private void txtTitulotxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitulotxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitulotxtTituloActionPerformed

    private void btnAceptarbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarbtnAceptarActionPerformed
        ClassPublicaciones p = new ClassPublicaciones();
        ClassLibro pe= new ClassLibro();
        String titulo,autor,fecha,ISBN,Ediccion;
        int nPaginas;
        double precio;
        titulo= txtTitulo.getText();
        autor = txtAutor.getText();
        nPaginas= Integer.parseInt(txtNPaginas.getText());
        precio= Double.parseDouble(txtPrecio.getText());
        ISBN = txtISBN.getText();
        Ediccion= txtEdiccion.getText();

        ManPublic mp = new ManPublic(titulo,precio,nPaginas,autor);
        mp.alta(ISBN, autor,Ediccion);

        txtTitulo.setText("");
        txtAutor.setText("");
        txtNPaginas.setText("");
        txtPrecio.setText("");
        txtEdiccion.setText("");
        txtISBN.setText("");

        
        JOptionPane.showMessageDialog(this, "Registro exitoso", "registro",
            JOptionPane.INFORMATION_MESSAGE);
        /*
        p.setAutor(autor);
        p.setPrecio(precio);
        p.setTitulo(titulo);
        p.setnPaginas(nPaginas);
        pe.setEdiccion(Ediccion);
        pe.setISBN(ISBN);*/
    }//GEN-LAST:event_btnAceptarbtnAceptarActionPerformed

    private void btnCancelarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarjButton1ActionPerformed
        txtTitulo.setText("");
        txtAutor.setText("");
        txtNPaginas.setText("");
        txtPrecio.setText("");
        txtEdiccion.setText("");
        txtISBN.setText("");
    }//GEN-LAST:event_btnCancelarjButton1ActionPerformed

    private void txtEdicciontxtEdiccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicciontxtEdiccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicciontxtEdiccionActionPerformed

    private void txtPreciotxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreciotxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreciotxtPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel cuerpo7;
    private javax.swing.JPanel encabezado;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel margen;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEdiccion;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNPaginas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    public Icon setIcono (String url, JButton btn1){
        //int ancho=89, alto=23;
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = btn1.getWidth();
        int alto = btn1.getHeight();
        //dar parametros a el icono
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho,alto, Image.SCALE_DEFAULT));
        
        return icono;
    }
    
    //dar efecto al boton
    public Icon setBotonPresionado(String url, JButton btn1, int ancho, int alto){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        //lo que se reducira respecto a la imagen original
        int width = btn1.getWidth() - ancho;
        int height = btn1.getHeight()- alto;
        
        ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
        return icono;
        
    }
     class fondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/textura_libroA.jpg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
     class fondoPanel1 extends JPanel{
        private Image imagen;
        
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/libro1.jpg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
     class fondoPanel2 extends JPanel{
        private Image imagen;
        
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/libro2_1.jpg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
}
