/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



import java.awt.Graphics;
import java.awt.Image;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vargas Baltazar
 */
public class Principal extends javax.swing.JFrame{
    
    PanelVista vista;
    fondoPanel fondo = new fondoPanel();
    Consultar c;
    public Principal() {
        
        initComponents();
       this.setContentPane(fondo); 
       fondo.add(Contenedor1);
       //Contenedor1.setVisible(false);
       
       vista = new PanelVista();
       Contenedor1.add(vista);
       vista.setVisible(false);
       
       c = new Consultar();
       Contenedor1.add(c);
       c.setVisible(false);
        
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jDialog1 = new javax.swing.JDialog();
        Contenedor1 = new fondoPanel2();
        jMenuBar1 = new javax.swing.JMenuBar();
        OpcPrincipal = new javax.swing.JMenu();
        main = new javax.swing.JMenuItem();
        OpcSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        OpcAgregar = new javax.swing.JMenuItem();
        OpcConsultar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        OpcProgramer = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 670));
        setResizable(false);

        Contenedor1.setMinimumSize(new java.awt.Dimension(400, 470));
        Contenedor1.setPreferredSize(new java.awt.Dimension(490, 530));
        Contenedor1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Contenedor1, java.awt.BorderLayout.PAGE_START);

        OpcPrincipal.setText("Principal");
        OpcPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcPrincipalActionPerformed(evt);
            }
        });

        main.setText("Principal");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });
        OpcPrincipal.add(main);

        OpcSalir.setText("Salir");
        OpcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcSalirActionPerformed(evt);
            }
        });
        OpcPrincipal.add(OpcSalir);

        jMenuBar1.add(OpcPrincipal);

        jMenu2.setText("Opciones");

        OpcAgregar.setText("Agregar");
        OpcAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(OpcAgregar);

        OpcConsultar.setText("Consultar");
        OpcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(OpcConsultar);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Info");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        OpcProgramer.setText("Programador");
        OpcProgramer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcProgramerActionPerformed(evt);
            }
        });
        jMenu1.add(OpcProgramer);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void OpcAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcAgregarActionPerformed
        
        Contenedor1.add(vista);
      // Contenedor1.setVisible(true);
        c.setVisible(false);
        vista.setVisible(true);
        
        
      
        
    }//GEN-LAST:event_OpcAgregarActionPerformed

    private void OpcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_OpcSalirActionPerformed

    private void OpcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcConsultarActionPerformed
        c.mostrarDatos();
        vista.setVisible(false);
        Contenedor1.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_OpcConsultarActionPerformed

    private void OpcPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcPrincipalActionPerformed
       
      // this.setContentPane(fondo); 
      //  Contenedor1.setVisible(false);
      //Contenedor1.setVisible(false);
    }//GEN-LAST:event_OpcPrincipalActionPerformed

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        vista.setVisible(false);
        c.setVisible(false);
    }//GEN-LAST:event_mainActionPerformed

    private void OpcProgramerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcProgramerActionPerformed
        JOptionPane.showMessageDialog(this, "\n"
                + "Vargas Baltazar Alma Delia\n"
                + "", "Info",
                JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_OpcProgramerActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor1;
    private javax.swing.JMenuItem OpcAgregar;
    private javax.swing.JMenuItem OpcConsultar;
    private javax.swing.JMenu OpcPrincipal;
    private javax.swing.JMenuItem OpcProgramer;
    private javax.swing.JMenuItem OpcSalir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenuItem main;
    // End of variables declaration//GEN-END:variables

    class fondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
    class fondoPanel2 extends JPanel{
        private Image imagen;
        
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/libro_corazon.jpg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
    
    
    
}
//imagenes obtenidas de la plataforma 
//https://www.istockphoto.com/
